networks:
  backuphub_network:
    external: true

services:
  app: &app
    build:
      context: .
      dockerfile: compose/Dockerfile
    container_name: app_${STAGE}
    command: /start
    restart: always
    env_file:
      - ./env
    volumes:
      - /opt/backuphub/static:/opt/bh/vol/static
    expose:
      - "8000"
    networks:
      - backuphub_network

  celery_worker:
    <<: *app
    container_name: celery_worker_${STAGE}
    command: /start-celeryworker
    volumes: []
    expose: []

  celery_beat:
    <<: *app
    container_name: celery_beat_${STAGE}
    command: /start-celerybeat
    volumes: []
    expose: []

  flower:
    <<: *app
    container_name: flower_${STAGE}
    command: /start-flower
    volumes: []
    expose:
      - "5555"
    depends_on:
      - celery_worker
      - celery_beat
