version: '3.9'

networks:
  backuphub_network:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: compose/Dockerfile
    container_name: app
    restart: unless-stopped
    env_file:
      - ./env
    volumes:
      - ./app:/opt/bh/
    ports:
      - "8000:8000"
    networks:
      - backuphub_network


