version: '3.9'

networks:
  backuphub_network:
    external: true

services:
  app: &app
    build:
      context: .
      dockerfile: compose/Dockerfile
    container_name: app_${STAGE}
    command: /start
    restart: always
    env_file:
      - ./env
    expose:
      - "8000"
    networks:
      - backuphub_network

