version: '3.9'

networks:
  backuphub_network:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: compose/Dockerfile
    container_name: app_${STAGE}
    restart: unless-stopped
    env_file:
      - ./env
    expose:
      - "8000"
    networks:
      - backuphub_network


