# Generated by Django 5.0.7 on 2026-07-13 23:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="System name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "api_key",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Automatically generated upon creation.",
                        unique=True,
                        verbose_name="API Key",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_systems",
                        to="dictionaries.environment",
                        verbose_name="Environment",
                    ),
                ),
                (
                    "system_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_systems",
                        to="dictionaries.systemtype",
                        verbose_name="System type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target System",
                "verbose_name_plural": "Target Systems",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TargetSystemVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Version number"),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Owner"
                    ),
                ),
                (
                    "administrator",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Administrator",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Is current"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Valid from"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid to"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "target_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="systems.targetsystem",
                        verbose_name="Target system",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Version",
                "verbose_name_plural": "System Versions",
                "ordering": ["target_system", "-version_number"],
                "unique_together": {("target_system", "version_number")},
            },
        ),
    ]
