# Generated by Django 5.2 on 2026-07-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0002_informationsystem"),
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetsystem",
            name="information_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_systems",
                to="dictionaries.informationsystem",
                verbose_name="Information System",
            ),
        ),
    ]
