# Generated by Django 5.0.7 on 2026-07-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tool name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Tool",
                "verbose_name_plural": "Backup Tools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Environment name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
            ],
            options={
                "verbose_name": "Environment",
                "verbose_name_plural": "Environments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="System type name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Type",
                "verbose_name_plural": "System Types",
                "ordering": ["name"],
            },
        ),
    ]
