# Generated by Django 5.2 on 2026-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionaries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformationSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Information system name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
            ],
            options={
                "verbose_name": "Information System",
                "verbose_name_plural": "Information Systems",
                "ordering": ["name"],
            },
        ),
    ]
