# Generated by Django 5.0.7 on 2026-07-13 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_job_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="External job ID",
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Hostname"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started at"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "size_bytes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Size (bytes)"
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Storage type",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Backup file path",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="Metadata"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error message"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "backup_configuration_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="configurations.backupconfigurationversion",
                        verbose_name="Configuration version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Operation",
                "verbose_name_plural": "Backup Operations",
                "ordering": ["-started_at"],
            },
        ),
    ]
