# Generated by Django 5.2 on 2026-07-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupoperation",
            name="size_bytes",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Size (bytes)"
            ),
        ),
    ]
