[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
addopts =
    --reuse-db
    --nomigrations
    -v
    --tb=short
    --strict-markers
    --disable-warnings
    --maxfail=1
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests
    web: marks tests for web views
    api: marks tests for API views