# Generated by Django 5.2.15 on 2026-07-01 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('system_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='API-ключ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'target_system',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='Имя хоста')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('target_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='core.targetsystem', verbose_name='Наблюдаемая система')),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID операции')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('in_progress', 'В процессе')], max_length=20, verbose_name='Статус')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('backup_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер (байты)')),
                ('storage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Используемое хранилище')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='Технические данные')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='core.host', verbose_name='Сервер')),
                ('target_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.targetsystem', verbose_name='Система')),
            ],
            options={
                'db_table': 'backup',
            },
        ),
    ]
