# Generated by Django 5.2.15 on 2026-07-06 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название типа"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип системы",
                "verbose_name_plural": "Типы систем",
                "db_table": "system_type",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="backup",
            options={"verbose_name": "Backup", "verbose_name_plural": "Backups"},
        ),
        migrations.AlterModelOptions(
            name="host",
            options={"verbose_name": "Host", "verbose_name_plural": "Hosts"},
        ),
        migrations.AlterModelOptions(
            name="targetsystem",
            options={
                "verbose_name": "Target System",
                "verbose_name_plural": "Target Systems",
            },
        ),
        migrations.AlterField(
            model_name="backup",
            name="backup_size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Size (bytes)"
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End time"),
        ),
        migrations.AlterField(
            model_name="backup",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="Error message"),
        ),
        migrations.AlterField(
            model_name="backup",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backups",
                to="core.host",
                verbose_name="Server",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID operation",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="meta_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Technical data"
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="start_time",
            field=models.DateTimeField(verbose_name="Start time"),
        ),
        migrations.AlterField(
            model_name="backup",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("error", "Error"),
                    ("in_progress", "In progress"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="storage",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Storage used"
            ),
        ),
        migrations.AlterField(
            model_name="backup",
            name="target_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backups",
                to="core.targetsystem",
                verbose_name="System",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="hostname",
            field=models.CharField(max_length=255, verbose_name="Name host"),
        ),
        migrations.AlterField(
            model_name="host",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="IP-addres"),
        ),
        migrations.AlterField(
            model_name="host",
            name="target_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosts",
                to="core.targetsystem",
                verbose_name="Observed system",
            ),
        ),
        migrations.AlterField(
            model_name="targetsystem",
            name="api_key",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="API Key"
            ),
        ),
        migrations.AlterField(
            model_name="targetsystem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="targetsystem",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="targetsystem",
            name="system_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="systems",
                to="core.systemtype",
                verbose_name="System type",
            ),
        ),
    ]
