<<<<<<< HEAD
# Generated by Django 5.2.15 on 2026-07-09 14:31
=======
# Generated by Django 5.2.15 on 2026-07-08 11:40
>>>>>>> a67310cbd931e2983732da421f7c49ad20bc40e0

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemtype_alter_backup_options_alter_host_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Configuration name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Configuration",
                "verbose_name_plural": "Backup Configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BackupTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tool name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Tool",
                "verbose_name_plural": "Backup Tools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Environment name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
            ],
            options={
                "verbose_name": "Environment",
                "verbose_name_plural": "Environments",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="host",
            name="target_system",
        ),
        migrations.AlterModelOptions(
            name="systemtype",
            options={
                "ordering": ["name"],
                "verbose_name": "System Type",
                "verbose_name_plural": "System Types",
            },
        ),
        migrations.AlterModelOptions(
            name="targetsystem",
            options={
                "ordering": ["name"],
                "verbose_name": "Target System",
                "verbose_name_plural": "Target Systems",
            },
        ),
        migrations.AddField(
            model_name="systemtype",
            name="created_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Created by"
            ),
        ),
        migrations.AddField(
            model_name="systemtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="systemtype",
            name="updated_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Updated by"
            ),
        ),
        migrations.AddField(
            model_name="targetsystem",
            name="created_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Created by"
            ),
        ),
        migrations.AddField(
            model_name="targetsystem",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="targetsystem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="targetsystem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AddField(
            model_name="targetsystem",
            name="updated_by",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Updated by"
            ),
        ),
        migrations.AlterField(
            model_name="systemtype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="systemtype",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="systemtype",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="System type name"
            ),
        ),
        migrations.AlterField(
            model_name="targetsystem",
            name="api_key",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Automatically generated upon creation.",
                unique=True,
                verbose_name="API Key",
            ),
        ),
        migrations.AlterField(
            model_name="targetsystem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="targetsystem",
            name="name",
            field=models.CharField(max_length=255, verbose_name="System name"),
        ),
        migrations.AlterField(
            model_name="targetsystem",
            name="system_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_systems",
                to="core.systemtype",
                verbose_name="System type",
            ),
        ),
        migrations.AlterModelTable(
            name="systemtype",
            table=None,
        ),
        migrations.AlterModelTable(
            name="targetsystem",
            table=None,
        ),
        migrations.CreateModel(
            name="BackupConfigurationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Version number"),
                ),
                (
                    "backup_mode",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("incremental", "Incremental"),
                            ("differential", "Differential"),
                            ("physical", "Physical"),
                            ("logical", "Logical"),
                        ],
                        default="full",
                        max_length=50,
                        verbose_name="Backup mode",
                    ),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Schedule (cron)",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Retention period (days)"
                    ),
                ),
                (
                    "rpo_minutes",
                    models.PositiveIntegerField(
                        default=1440, verbose_name="RPO (minutes)"
                    ),
                ),
                (
                    "rto_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="RTO (minutes)"
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("s3", "Amazon S3"),
                            ("azure", "Azure Blob Storage"),
                            ("gcs", "Google Cloud Storage"),
                            ("nfs", "NFS"),
                            ("other", "Other"),
                        ],
                        default="local",
                        max_length=50,
                        verbose_name="Storage type",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Storage path",
                    ),
                ),
                (
                    "verify_after_backup",
                    models.BooleanField(
                        default=False, verbose_name="Verify after backup"
                    ),
                ),
                (
                    "immutable_storage",
                    models.BooleanField(
                        default=False, verbose_name="Immutable storage"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Is current"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valid from")),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid to"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "backup_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.backupconfiguration",
                        verbose_name="Backup configuration",
                    ),
                ),
                (
                    "backup_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuration_versions",
                        to="core.backuptool",
                        verbose_name="Backup tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Configuration Version",
                "verbose_name_plural": "Backup Configuration Versions",
                "ordering": ["backup_configuration", "-version_number"],
                "unique_together": {("backup_configuration", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="BackupOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_job_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="External job ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255, verbose_name="Hostname")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Started at")),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished at"
                    ),
                ),
                (
                    "size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Size (bytes)"
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Storage type",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Backup file path",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="Metadata"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error message"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "backup_configuration_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="core.backupconfigurationversion",
                        verbose_name="Configuration version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Operation",
                "verbose_name_plural": "Backup Operations",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="targetsystem",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_systems",
                to="core.environment",
                verbose_name="Environment",
            ),
        ),
        migrations.CreateModel(
            name="TargetSystemVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Version number"),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Owner"
                    ),
                ),
                (
                    "administrator",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Administrator",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Is current"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valid from")),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid to"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "target_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.targetsystem",
                        verbose_name="Target system",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Version",
                "verbose_name_plural": "System Versions",
                "ordering": ["target_system", "-version_number"],
                "unique_together": {("target_system", "version_number")},
            },
        ),
        migrations.AddField(
            model_name="backupconfiguration",
            name="target_system_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="backup_configurations",
                to="core.targetsystemversion",
                verbose_name="System version",
            ),
        ),
        migrations.DeleteModel(
            name="Backup",
        ),
        migrations.DeleteModel(
            name="Host",
        ),
    ]
