# Generated by Django 5.2.15 on 2026-07-06 13:38

from django.db import migrations

def add_initial_system_types(apps, schema_editor):
    # Получаем модель SystemType
    SystemType = apps.get_model('core', 'SystemType')
    
    # Список типов для добавления
    types = [
        ('PostgreSQL Production', 'Production PostgreSQL database'),
        ('PostgreSQL Test', 'Test PostgreSQL database'),
        ('GitLab', 'GitLab server'),
        ('ERP System', 'Enterprise Resource Planning system'),
        ('File Storage', 'File storage server'),
        ('Kubernetes Cluster', 'Kubernetes cluster'),
        ('MySQL Production', 'Production MySQL database'),
        ('MongoDB', 'MongoDB database'),
        ('Redis', 'Redis cache server'),
        ('Web Server (Nginx/Apache)', 'Web server (Nginx/Apache)'),
        ('Application Server', 'Application server'),
        ('Message Queue (RabbitMQ/Kafka)', 'Message queue system (RabbitMQ/Kafka)'),
    ]

    # Добавляем каждый тип в базу
    for name, description in types:
        SystemType.objects.get_or_create(
            name=name, 
            defaults={'description': description}
        )

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemtype_alter_backup_options_alter_host_options_and_more"),
    ]

    operations = [
        migrations.RunPython(add_initial_system_types, migrations.RunPython.noop),
    ]
