# Generated by Django 5.2.16 on 2026-07-10 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_backupconfiguration_backuptool_environment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupconfigurationversion",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid from"
            ),
        ),
        migrations.AlterField(
            model_name="targetsystemversion",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid from"
            ),
        ),
    ]
