# Generated by Django 5.2.16 on 2026-07-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_backupconfigurationversion_valid_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupoperation",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Started at"),
        ),
    ]
