# Generated by Django 5.2.16 on 2026-07-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_backupoperation_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupoperation",
            name="hostname",
            field=models.CharField(blank=True, max_length=255, verbose_name="Hostname"),
        ),
    ]
