# Generated by Django 5.0.7 on 2026-07-13 23:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dictionaries", "0001_initial"),
        ("systems", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Configuration name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Updated by"
                    ),
                ),
                (
                    "target_system_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="backup_configurations",
                        to="systems.targetsystemversion",
                        verbose_name="System version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Configuration",
                "verbose_name_plural": "Backup Configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BackupConfigurationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Version number"),
                ),
                (
                    "backup_mode",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("incremental", "Incremental"),
                            ("differential", "Differential"),
                            ("physical", "Physical"),
                            ("logical", "Logical"),
                        ],
                        default="full",
                        max_length=50,
                        verbose_name="Backup mode",
                    ),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Schedule (cron)",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Retention period (days)"
                    ),
                ),
                (
                    "rpo_minutes",
                    models.PositiveIntegerField(
                        default=1440, verbose_name="RPO (minutes)"
                    ),
                ),
                (
                    "rto_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="RTO (minutes)"
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("s3", "Amazon S3"),
                            ("azure", "Azure Blob Storage"),
                            ("gcs", "Google Cloud Storage"),
                            ("nfs", "NFS"),
                            ("other", "Other"),
                        ],
                        default="local",
                        max_length=50,
                        verbose_name="Storage type",
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Storage path",
                    ),
                ),
                (
                    "verify_after_backup",
                    models.BooleanField(
                        default=False, verbose_name="Verify after backup"
                    ),
                ),
                (
                    "immutable_storage",
                    models.BooleanField(
                        default=False, verbose_name="Immutable storage"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Is current"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Valid from"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid to"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Created by"
                    ),
                ),
                (
                    "backup_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="configurations.backupconfiguration",
                        verbose_name="Backup configuration",
                    ),
                ),
                (
                    "backup_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuration_versions",
                        to="dictionaries.backuptool",
                        verbose_name="Backup tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Configuration Version",
                "verbose_name_plural": "Backup Configuration Versions",
                "ordering": ["backup_configuration", "-version_number"],
                "unique_together": {("backup_configuration", "version_number")},
            },
        ),
    ]
