name: DevSecOps Pipeline

on:
  push:
    branches:
      - DEV

jobs:

  security-and-build:
    runs-on: [self-hosted, secops]

    steps:
      - uses: actions/checkout@v4

      - name: Load Environment
        run: grep -v '^#' /opt/backuphub/.env >> $GITHUB_ENV

      - name: Cleanup
        run: |
          docker system prune -af || true
          docker builder prune -af || true

      - name: Semgrep Scan
        run: |
          docker compose -f /opt/backuphub/devsecops/docker-compose.yml run --rm \
            -v ${{ github.workspace }}:/src \
            sast-semgrep \
            semgrep scan \
            --config=p/owasp-top-10 \
            --metrics=off \
            --json \
            --output=/src/sast.json \
            /src || true

      - name: Build Image
        run: |
          docker build \
            --no-cache \
            -t $REGISTRY_URL/backuphub/app:${{ github.sha }} \
            -f compose/Dockerfile .

      - name: Docker Login
        run: |
          echo "$REGISTRY_PASSWORD" | docker login \
            $REGISTRY_URL \
            -u "$REGISTRY_USER" \
            --password-stdin

      - name: Grype Scan
        run: |
          docker compose -f /opt/backuphub/devsecops/docker-compose.yml run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}:/src \
            sca-grype \
            $REGISTRY_URL/backuphub/app:${{ github.sha }} \
            -o json \
            --file /src/sca.json || true

      - name: Push Image
        run: |
          docker push $REGISTRY_URL/backuphub/app:${{ github.sha }}
          docker tag \
            $REGISTRY_URL/backuphub/app:${{ github.sha }} \
            $REGISTRY_URL/backuphub/app:dev-latest
          docker push $REGISTRY_URL/backuphub/app:dev-latest

      - name: Upload Reports to DefectDojo
        if: always()
        run: |

          SCAN_DATE=$(date +%F)

          if [ -f "${{ github.workspace }}/sast.json" ]; then
            curl --fail \
              -X POST "$DOJO_URL/api/v2/import-scan/" \
              -H "Authorization: Token $DOJO_TOKEN" \
              -F scan_type="Semgrep JSON Report" \
              -F file=@${{ github.workspace }}/sast.json \
              -F product_id=$DOJO_PRODUCT_ID \
              -F engagement_name=Build-${{ github.run_number }} \
              -F scan_date=$SCAN_DATE \
              -F auto_create_context=true
          fi

          if [ -f "${{ github.workspace }}/sca.json" ]; then
            curl --fail \
              -X POST "$DOJO_URL/api/v2/import-scan/" \
              -H "Authorization: Token $DOJO_TOKEN" \
              -F scan_type="Anchore Grype" \
              -F file=@${{ github.workspace }}/sca.json \
              -F product_id=$DOJO_PRODUCT_ID \
              -F engagement_name=Build-${{ github.run_number }} \
              -F scan_date=$SCAN_DATE \
              -F auto_create_context=true
          fi

      - name: Cleanup
        if: always()
        run: |
          docker system prune -af || true

  deploy:

    needs: security-and-build

    runs-on: [self-hosted, dev]

    steps:

      - name: Load Environment
        run: grep -v '^#' /opt/backuphub/.env >> $GITHUB_ENV

      - name: Deploy
        run: |

          echo "$REGISTRY_PASSWORD" | docker login \
            $REGISTRY_URL \
            -u "$REGISTRY_USER" \
            --password-stdin

          cd /opt/backuphub/app

          sed -i \
          "s|image: .*|image: $REGISTRY_URL/backuphub/app:${{ github.sha }}|" \
          deploy.docker-compose.yml

          docker compose -f deploy.docker-compose.yml pull
          docker compose -f deploy.docker-compose.yml up -d

          docker image prune -af

  dast:

    needs: deploy

    runs-on: [self-hosted, secops]

    steps:

      - name: Load Environment
        run: grep -v '^#' /opt/backuphub/.env >> $GITHUB_ENV

      - name: Pull ZAP
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run ZAP Baseline
        run: |

          docker run --rm \
            -v ${{ github.workspace }}:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t $APP_URL_DEV \
            -J /zap/wrk/dast.json || true

      - name: Upload ZAP Report
        if: always()
        run: |

          SCAN_DATE=$(date +%F)

          if [ -f "${{ github.workspace }}/dast.json" ]; then

            curl --fail \
              -X POST "$DOJO_URL/api/v2/import-scan/" \
              -H "Authorization: Token $DOJO_TOKEN" \
              -F scan_type="ZAP Scan" \
              -F file=@${{ github.workspace }}/dast.json \
              -F product_id=$DOJO_PRODUCT_ID \
              -F engagement_name=Build-${{ github.run_number }} \
              -F scan_date=$SCAN_DATE \
              -F auto_create_context=true

          fi

      - name: Cleanup
        if: always()
        run: |
          docker system prune -af
